// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Budget struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Description  string         `json:"description"`
	Amount       float64        `json:"amount"`
	CreatedAt    string         `json:"createdAt"`
	UpdatedAt    string         `json:"updatedAt"`
	UserBudgets  []*UserBudget  `json:"userBudgets"`
	Transactions []*Transaction `json:"transactions"`
}

type Category struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Description  string         `json:"description"`
	CreatedAt    string         `json:"createdAt"`
	UpdatedAt    string         `json:"updatedAt"`
	Transactions []*Transaction `json:"transactions"`
}

type NewBudgetInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Amount      float64 `json:"amount"`
}

type NewCategoryInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewTransactionInput struct {
	Title      string  `json:"title"`
	BudgetID   string  `json:"budgetId"`
	CategoryID string  `json:"categoryId"`
	Amount     float64 `json:"amount"`
	Type       string  `json:"type"`
}

type NewUserBudgetInput struct {
	UserID    string `json:"userId"`
	BudgetID  string `json:"budgetId"`
	Ownership bool   `json:"ownership"`
	ReadOnly  bool   `json:"readOnly"`
}

type NewUserInput struct {
	FirstName         string `json:"firstName"`
	LastName          string `json:"lastName"`
	Email             string `json:"email"`
	EncryptedPassword string `json:"encryptedPassword"`
}

type Transaction struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Budget    *Budget   `json:"budget"`
	Category  *Category `json:"category"`
	Amount    float64   `json:"amount"`
	Type      string    `json:"type"`
	CreatedAt string    `json:"createdAt"`
	UpdatedAt string    `json:"updatedAt"`
}

type UpdateBudgetInput struct {
	Name        *string  `json:"name"`
	Description *string  `json:"description"`
	Amount      *float64 `json:"amount"`
}

type UpdateCategoryInput struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
}

type UpdateTransactionInput struct {
	Title      *string  `json:"title"`
	BudgetID   *string  `json:"budgetId"`
	CategoryID *string  `json:"categoryId"`
	Amount     *float64 `json:"amount"`
	Type       *string  `json:"type"`
}

type UpdateUserBudgetInput struct {
	Ownership *bool `json:"ownership"`
	ReadOnly  *bool `json:"readOnly"`
}

type UpdateUserInput struct {
	FirstName         *string `json:"firstName"`
	LastName          *string `json:"lastName"`
	Email             *string `json:"email"`
	EncryptedPassword *string `json:"encryptedPassword"`
}

type User struct {
	ID                string    `json:"id"`
	FirstName         string    `json:"firstName"`
	LastName          string    `json:"lastName"`
	Email             string    `json:"email"`
	EncryptedPassword string    `json:"encryptedPassword"`
	Budgets           []*Budget `json:"budgets"`
}

type UserBudget struct {
	ID        string  `json:"id"`
	User      *User   `json:"user"`
	Budget    *Budget `json:"budget"`
	Ownership bool    `json:"ownership"`
	ReadOnly  bool    `json:"readOnly"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}
